### PR TITLE
fix _WIDTH for negative values

### PR DESCRIPTION
**Pull request by sebdelsol**
fix bug #11

### CODE REVIEW

**Comment by gazoodle** [comment]
This library was written using TDD, so could you add an appropriate test for this behaviour in StreamingTests.ino?

**Comment by sebdelsol** [comment]
> This library was written using TDD, so could you add an appropriate test for this behaviour in StreamingTests.ino?

I've added tests for :

-  _WIDTH with negatives values that failed without the fix
- _FLOATW

**Comment by peterpolidoro** [comment]
Hi. Thanks for all of the updates! Want me to merge now?

**Review by gazoodle — CHANGES_REQUESTED** [review]
On my Nano board (and I suspect all AVR boards), the test

    Assert << _FLOATW(-3.1415926, 6, 11) == F("  -3.141593");

Fails because the output is -3.141592.

I suspect this is because of the float accuracy on the processor is only 6/7 digits and therefore the constant supplied is truncated during compilation (float and double are the same on this platform).

I recommend something ugly like this ...

#ifdef ARDUINO_ARCH_AVR    
    Assert << _FLOATW(-3.1415926, 6, 11) == F("  -3.141592");
#else
    Assert << _FLOATW(-3.1415926, 6, 11) == F("  -3.141593");
#endif

**Comment by peterpolidoro** [comment]
Ok I updated the test like you suggested and bumped the version number again.

**Comment by gazoodle** [comment]
Thanks!

**Comment by sebdelsol** [comment]
> On my Nano board (and I suspect all AVR boards), the test [...] fails

Yes that was the issue with trying to count the number of digits of a double/float : it depends a lot on the actual implementation across all the boards. 

I've discovered that esp8266, esp32 and AVR don't use the same `Print::printFloat` implementation... and you've to handle nan, infinity and overflow... and you've to take into account the low level float accuracy... on top of that you'll have to check regularly the change in any of those different implementations... phew.   

So I ended up with a basic Print object that `Print::printFloat` the actual double/float in a buffer and gives you its size, then you just have to pad it. I was reluctant to do it since it has a buffer size limitation. But I guess a 32 chars buffer is good enough for 99% of use cases and it's only ~45 Bytes on the stack without any allocation that would fragment the memory further.

**Pull request merged**
